### ISSUE TITLE
Missing sources  due file size limitation

### ISSUE THREAD

**Issue by pauleve** [msoos/sat_competition_2013_sources#1]
Hello,

Because of the file size limitation, sources for the CSHC* solvers are missing (CSHCapplLC, CSHCapplLG, CSHCcombCS, CSHCrandMC)

For the [SAT Heritage](https://github.com/sat-heritage/docker-images) project, we plan to mirror all the sources of past SAT competitions on [Zenodo](https://zenodo.org) (see https://github.com/sat-heritage/docker-images/blob/master/SOURCES.md).
We would like to do the same with 2013.

Thus, I would be interested in the missing files :-)
A trick I found for github is to create a release; there you can attach files of any size to it https://github.com/sat-heritage/docker-images/releases/tag/2021-competition);
could you do the same for attaching the CSHC* solvers? Or even directly create a complete Zenodo record with all the solver sources :-)

**Comment by msoos** [comment]
Hi!

First of all, please say hello to Roberto Di Cosmo! I had met him waaaay back when in Paris, and then accidentally in Singapore once. Must be great work with him. Regarding the sources: actually, they are all available along with the detailed results, here:

http://satcompetition.org/sc13solver.sql.xz (for 2013, i.e. this one)
http://satcompetition.org/sc14solver.sql.xz (for 2014)

What I did was to download & extract the files, then load them up to SQLite, then extract the binary data, and it was in there! It's actually a more complete dump this way than the sources themselves, although I do understand that you and most people would prefer the ZIP files extracted from the SQL, etc.

The ZIP files that are missing from this GitHub (along with the other table dumps like solve times, etc) are:

```
386M    102-CSHCpar8-YuriMalitsky_and_AshishSabharwal_and_HorstSamulowitz_and_MeinolfSellmann.zip
71M     103-CSHCapplLC-YuriMalitsky_and_AshishSabharwal_and_HorstSamulowitz_and_MeinolfSellmann.zip
24M     97-CSHCcombCS-YuriMalitsky_and_AshishSabharwal_and_HorstSamulowitz_and_MeinolfSellmann.zip
58M     98-CSHCrandMC-YuriMalitsky_and_AshishSabharwal_and_HorstSamulowitz_and_MeinolfSellmann.zip
73M     99-CSHCapplLG-YuriMalitsky_and_AshishSabharwal_and_HorstSamulowitz_and_MeinolfSellmann.zip
```

But they are all in the XZ files above. Would you be so kind as to have a go at extracting these files? I don't have them anymore and it'd be quite a bit of work to do it, to be honest. That way you can also get the raw SQL data of the competition, runtimes, etc :)

Cheers,

Mate

**Comment by pauleve** [comment]
Thanks a lot for the links.
I've extracted the sc13 sources at https://zenodo.org/record/5776223 and sc14 at https://zenodo.org/record/5776517
It seems that the sql files only contain the blobs and general metadata on the solvers, but nothing from the solve times, parameters, etc. (although part of them can be recovered from https://web.archive.org/web/20160714003055/http://satcompetition.org/2013) But for now, it is already great to have all the sources back :-)

**Comment by msoos** [comment]
Thanks so much for the work! Sorry, I was so incredibly overwhelmed with work I simply couldn't help :( Thanks again,

Mate
